// src/components/work/Kaleidosync.vue
<template lang="pug">
.kaleidosync(:class="{ active }")
  Item(:namespace="namespace" :total="total" :active="active")
    h2 Kaleidosync
    p A Spotify web client &amp; customizable WebGL visualizer.
    .ctas  
      a(href="https://kaleidosync-beta.herokuapp.com/" target="kaleidosync") View Project
      ViewToggle
</template>

<script>
import workItem from '@/mixins/work-item'

export default {
  mixins: [workItem],
  data: () => ({
    namespace: 'kaleidosync',
    total: 5
  })
}
</script>

<style lang="scss" scoped>
.kaleidosync {
  @include work-item;
}

.ctas {
  @include flex;
  margin-top: $base-margin;
}
</style>

// src/pages/work/screens/Kaleidosync.jsx
import React from 'react'
import './Kaleidosync.scss'

const Kaleidosync = () => (
  <div className="Kaleidosync">
    <div className="text">
      <h2>Kaleidosync</h2>
      <p>A web-based Spotify visualizer.</p>
      <a href="https://kaleidosync.herokuapp.com" target="_blank" rel="noopener noreferrer">View Project</a>
    </div>
    <canvas id="kaleidoscope"></canvas>
  </div>
)

export default Kaleidosync
