// src/components/work/Kaleidosync.vue
<template lang="pug">
.kaleidosync(:class="{ active }" @transitionend="$emit('transition-end')")
  WorkItem(:namespace="namespace" :total="total" :active="active" :ctas="ctas")
    template(v-slot:content)
      h2: span Kaleidosync
      p: span A Spotify web client &amp; customizable WebGL visualizer.
</template>

<script>
import workItem from '@/mixins/work-item'

export default {
  mixins: [workItem],
  data: () => ({
    namespace: 'kaleidosync',
    total: 5,
    ctas: {
      href: 'https://kaleidosync-beta.herokuapp.com',
      target: 'kaleidosync',
      text: 'View Project',
      margin: false
    }
  })
}
</script>

// src/components/Kaleidosync.jsx
import React from 'react'
import '../styles/components/kaleidosync.css'

const Kaleidosync = (props) => (
  <div className={props.playing ? 'kaleidosync playing' : 'kaleidosync'}>
    <div className="text">
      <h2>Kaleidosync</h2>
      <p>A web-based Spotify visualizer.</p>
      <button onClick={props.buttonClick}>
        { !props.playing && <span>Demo</span> }
        { props.playing && <span>Stop</span> }
      </button> 
      <a href="https://kaleidosync.herokuapp.com" target="_blank">View Project</a>
    </div>
    <canvas id="kaleidoscope"></canvas>
    <audio></audio>
  </div>
)

export default Kaleidosync
